"""Generation pipeline + app runtime state (the Dynasty+ companion).

Responsibilities:
  * Own the "current" dynasty pointer (year/week).
  * Read dynasty state from the save file the Simulator (or, later, CFB 27)
    writes; archive each week's snapshot so past weeks stay browsable.
  * Run a single module or the full slate, caching results per week.
  * Feed factual summaries into the narrative memory layer for continuity.
  * React to save changes (new week, new season, same-week edit) via the watcher.
"""
from __future__ import annotations

import json
import threading
from pathlib import Path
from typing import Any

from . import cache, config, dynasty_paths, llm_settings, mock_data, narrative, progress, schema
from .modules import REGISTRY

_lock = threading.Lock()

# Per-(module, year, week) single-flight guard for the on-demand generate_module path.
# The frontend requests several modules at once when a dynasty opens, and each tab can
# re-request on remount; without coalescing, a cache miss lets every concurrent request
# launch its own generation of the same module and they thrash the local model. The
# first caller generates while the rest wait, then the double-checked cache serves them.
# (run_full uses the global _lock for the batch path; this covers the per-tab path.)
_module_locks: dict[tuple[str, int, int], threading.Lock] = {}
_module_locks_guard = threading.Lock()


def _module_lock(module_key: str, year: int, week: int) -> threading.Lock:
    key = (module_key, year, week)
    with _module_locks_guard:
        lk = _module_locks.get(key)
        if lk is None:
            lk = _module_locks[key] = threading.Lock()
        return lk


# Per-dynasty runtime state lives at data/dynasties/<id>/state.json (see
# _state_file): the pointer + last_coach + last_seen_hash + local_media_team, all
# of which are specific to one dynasty.

# Where the Simulator (or the real game) writes the live dynasty save we watch.
_SAVE_PATH = Path(config.SAVE_PATH)
# Per-week snapshots of the save, so browsing a past week shows that week's
# dynasty rather than the live one. The generated module content (cache.py) is
# the historical record; this keeps the raw dynasty dict consistent alongside it.
# Snapshots live at data/dynasties/<id>/archive/<year>/<week>.json.

# Modules held back when a post-game presser is owed: anything that reacts to the
# game or could quote the coach before he has spoken (the news feed, top stories,
# the inbound texts that react to the result, and the world's reactions to the
# week's breaking stories). They are generated by run_post_presser once the
# presser completes, so they reflect his answers from their very first run. (The phone
# roster itself is not held; inbound and news_reactions clear the phone cache when
# they deliver, so new texts surface after the news phase.)
HELD_FOR_PRESSER = ("top_stories", "news_feed", "inbound", "news_reactions")

# Pipeline run status, surfaced to the UI for the loading state.
_status: dict[str, Any] = {"running": False, "module": None, "progress": 0, "total": 0, "week": None}


# --- runtime app state (current pointer) ---------------------------------
def _state_file() -> Path:
    """The current dynasty's runtime state file, scoped under its own directory."""
    return dynasty_paths.current_root() / "state.json"


def _load_app_state() -> dict[str, Any]:
    path = _state_file()
    if path.exists():
        try:
            with path.open("r", encoding="utf-8") as fh:
                return json.load(fh)
        except (OSError, ValueError):
            pass
    return {"year": mock_data.SEASON_YEAR, "week": 10, "last_coach": None}


def _save_app_state(state: dict[str, Any]) -> None:
    path = _state_file()
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("w", encoding="utf-8") as fh:
            json.dump(state, fh, indent=2)
    except OSError:
        pass


def current_pointer() -> dict[str, int]:
    s = _load_app_state()
    return {"year": s["year"], "week": s["week"]}


def set_pointer(year: int, week: int) -> None:
    s = _load_app_state()
    s["year"], s["week"] = year, week
    _save_app_state(s)


def status() -> dict[str, Any]:
    return {**dict(_status), "sub_step": progress.get_sub_step()}


# --- dynasty loading ------------------------------------------------------
def _read_save() -> dict[str, Any] | None:
    """The live dynasty save the Simulator wrote, or None if there is none yet
    (cold start) or it fails validation (a torn/partial write)."""
    if not _SAVE_PATH.exists():
        return None
    try:
        with _SAVE_PATH.open("r", encoding="utf-8") as fh:
            data = json.load(fh)
    except (OSError, ValueError):
        return None
    if not isinstance(data, dict) or schema.validate(data):
        return None
    return data


def _archive(dynasty: dict[str, Any], year: int, week: int) -> None:
    """Snapshot a week's save under ITS OWN dynasty (keyed by meta.dynasty_id), so
    an archived week is always filed under the dynasty it belongs to, regardless of
    which dynasty is currently selected."""
    did = (dynasty.get("meta") or {}).get("dynasty_id")
    path = dynasty_paths.root_for(did) / "archive" / str(year) / f"{week}.json"
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("w", encoding="utf-8") as fh:
            json.dump(dynasty, fh, indent=2, default=str)
    except OSError:
        pass


def _read_archive(year: int, week: int) -> dict[str, Any] | None:
    path = dynasty_paths.current_root() / "archive" / str(year) / f"{week}.json"
    if not path.exists():
        return None
    try:
        with path.open("r", encoding="utf-8") as fh:
            return json.load(fh)
    except (OSError, ValueError):
        return None


def load_dynasty(year: int | None = None, week: int | None = None) -> dict[str, Any]:
    """Return the dynasty state for a (year, week).

    The current week comes from the live save the Simulator wrote; past weeks
    come from the per-week archive (snapshotted as each week was current). When
    no save exists yet (the Simulator has not run), fall back to a frozen seed
    dynasty so the companion is still usable.
    """
    ptr = current_pointer()
    year = year if year is not None else ptr["year"]
    week = week if week is not None else ptr["week"]

    save = _read_save()
    if save is not None:
        s_year = int(save["season"]["year"])
        s_week = int(save["season"]["week"])
        _archive(save, s_year, s_week)
        if (year, week) == (s_year, s_week):
            return save

    archived = _read_archive(year, week)
    if archived is not None:
        return archived
    if save is not None:
        return save  # best effort: the live state for an un-archived week
    return mock_data.generate(week=week, year=year)  # cold-start seed


def save_present() -> bool:
    return _read_save() is not None


def save_pointer() -> dict[str, Any]:
    """The save's CURRENT season/week + hash, independent of where the companion
    is pointed. The live watch compares this to the entered week to auto-advance
    when the Simulator (or the real game) moves the week forward."""
    save = _read_save()
    if save is None:
        return {"present": False, "year": None, "week": None, "hash": None}
    return {
        "present": True,
        "year": int(save["season"]["year"]),
        "week": int(save["season"]["week"]),
        "hash": save["meta"].get("hash"),
    }


# --- explicit scan (the user-driven handoff) ------------------------------
def scan() -> dict[str, Any]:
    """Read the save and register/update a dynasty (the Scan button). Sets the
    pointer to the save's week and archives the snapshot. Does NOT generate, so
    opening the app stays instant; tabs generate their content on demand."""
    from . import dynasties
    save = _read_save()
    if save is None:
        return {"present": False}
    s_year = int(save["season"]["year"])
    s_week = int(save["season"]["week"])
    _archive(save, s_year, s_week)
    entry = dynasties.upsert_from_save(save)
    set_pointer(s_year, s_week)
    state = _load_app_state()
    state["last_seen_hash"] = save["meta"].get("hash")
    # Seed the local media (outlets + beat writers) for whatever program the save
    # names, so only the user's school's real local writers cover it. Re-seeds
    # only when the active program changes, so manual edits to the local media
    # survive a re-scan of the same team. National media is left alone.
    team_name = (save.get("team") or {}).get("name")
    if team_name and state.get("local_media_team") != team_name:
        try:
            from . import customization, local_media
            if local_media.has_team(team_name):
                customization.apply_local_media(team_name)
                state["local_media_team"] = team_name
        except Exception:
            pass
    _save_app_state(state)
    return {"present": True, "dynasty": entry, "year": s_year, "week": s_week,
            "needs_generation": not is_week_cached(s_year, s_week),
            # True when the user's last game still owes a post-game presser, so the
            # frontend can open the presser instead of regenerating the whole week.
            "presser_owed": presser_owed(s_year, save)}


def select_dynasty(dynasty_id: str) -> dict[str, Any] | None:
    """Make a previously scanned dynasty current and point the app at its week."""
    from . import dynasties
    if not dynasties.set_current(dynasty_id):
        return None
    entry = dynasties.get(dynasty_id)
    if entry:
        set_pointer(entry["year"], entry["week"])
    return entry


# --- narrative seeding ----------------------------------------------------
def _seed_narrative(dynasty: dict, year: int, week: int) -> None:
    """Record factual anchors for the week so continuity accumulates."""
    entries: list[str] = []
    recent = dynasty["schedule"]["recent_results"]
    if recent:
        last = recent[0]
        loc = "vs" if last["home"] else "at"
        entries.append(f"{last['result']} {last['score']} {loc} {last['opponent']}")
    rk = dynasty["team"]["rankings"].get("cfp")
    if rk:
        entries.append(f"{dynasty['team']['name']} ranked No. {rk} in the CFP projection at {dynasty['team']['record']['overall']}")
    up = dynasty["schedule"]["upcoming"]
    entries.append(f"Next up: {'vs' if up['home'] else 'at'} {up['opponent']}")
    # National anchors, so the week's timeline (which feeds every generator) carries
    # the wider sport too: the biggest result, the AP No. 1, and the Heisman leader.
    entries += _national_anchors(dynasty)
    narrative.log_week(year, week, entries)

    # Seed a couple of persistent storylines once per week if not present.
    existing = {t["summary"] for t in narrative.load(year).get("threads", [])}
    targets = dynasty["recruiting"].get("targets") or []
    outgoing = dynasty["transfer_portal"].get("outgoing") or []
    seeds = [
        ("CFP watch", f"{dynasty['team']['name']} pushing for a playoff bid at {dynasty['team']['record']['overall']}."),
    ]
    if targets:
        seeds.append(("Recruiting", f"Top target {targets[0]['name']} set an official visit for Week {week}."))
    if outgoing:
        seeds.append(("Transfer portal", f"{outgoing[0]['name']} is rumored to be weighing the portal."))
    # The hottest seat in the country becomes a persistent national storyline (stable
    # text per coach so it is not re-seeded every week as his record ticks over).
    hot = sorted(
        ((c.get("hot_seat") or 0, c) for t, c in (dynasty.get("coaches") or {}).items()
         if isinstance(c, dict) and t != dynasty["team"]["name"] and not c.get("is_user")),
        key=lambda x: -x[0])
    if hot and hot[0][0] >= 80:
        c = hot[0][1]
        seeds.append(("Coaching carousel", f"{c.get('name')} at {c.get('team')} is squarely on the hot seat this season."))
    for cat, summary in seeds:
        if summary not in existing:
            narrative.add_thread(year, week=week, category=cat, summary=summary)


def _national_anchors(dynasty: dict) -> list[str]:
    """The week's national timeline anchors: the biggest non-user result, the AP
    No. 1, and the Heisman leader (with his line). Reuses the news module's
    result-ranking so the timeline matches what the feed leads with."""
    out: list[str] = []
    try:
        from .modules import news_feed
        big = news_feed._biggest_result(dynasty)
        if big:
            verb = "stunned" if big["upset"] else "beat"
            out.append(f"Nationally: {big['winner']} {verb} {big['loser']} {big['score']}.")
    except Exception:
        pass
    nat = dynasty.get("national") or {}
    ap = [r for r in (nat.get("ap_top25") or []) if r.get("team")]
    if ap:
        out.append(f"AP No. 1: {ap[0]['team']} ({ap[0].get('record', '')}).")
    heis = [h for h in (nat.get("heisman_frontrunners") or []) if h.get("name")]
    if heis:
        h = heis[0]
        out.append(f"Heisman leader: {h['name']} ({h.get('team', '')})"
                   + (f", {h['stat_line']}" if h.get("stat_line") else "") + ".")
    return out


def detect_coaching_change(dynasty: dict) -> str | None:
    """Compare the user's head coach to the last-seen one; return new name on change."""
    s = _load_app_state()
    current = dynasty["team"]["head_coach"]["name"]
    last = s.get("last_coach")
    s["last_coach"] = current
    _save_app_state(s)
    if last and last != current:
        return current
    return None


# --- generation -----------------------------------------------------------
def generate_module(module_key: str, *, year: int | None = None, week: int | None = None,
                    regenerate: bool = False) -> Any:
    if module_key not in REGISTRY:
        raise KeyError(f"unknown module: {module_key}")
    ptr = current_pointer()
    year = year if year is not None else ptr["year"]
    week = week if week is not None else ptr["week"]

    # Presser gate: while a post-game presser is owed for the current week, hold off
    # writing NEW coverage for the news/inbound modules so the coach speaks before
    # the post-game headlines are written (run_post_presser regenerates them once
    # he has). Keep the week's existing pre-game coverage on screen in the meantime
    # (serve the cache); only fall back to the held placeholder when nothing has
    # been generated for this week yet. Past (archived) weeks are never gated.
    is_current = year == ptr["year"] and week == ptr["week"]
    if is_current and module_key in HELD_FOR_PRESSER and presser_owed(year):
        cached = cache.get_module(year, week, module_key)
        if cached is not None:
            return cached
        return {"module": module_key, "source": "held", "held_for_presser": True}

    if not regenerate:
        cached = cache.get_module(year, week, module_key)
        if cached is not None:
            return cached

    # Coalesce concurrent first-load requests for the same module (see _module_lock):
    # one generates, the rest wait and pick up the cache it writes.
    with _module_lock(module_key, year, week):
        if not regenerate:
            cached = cache.get_module(year, week, module_key)
            if cached is not None:
                return cached
        dynasty = load_dynasty(year, week)
        _seed_narrative(dynasty, year, week)
        content = REGISTRY[module_key].generate(
            dynasty, year=year, week=week, use_llm=llm_settings.use_llm(), regenerate=regenerate
        )
        cache.set_module(year, week, module_key, content)
        return content


def presser_owed(year: int, dynasty: dict[str, Any] | None = None) -> bool:
    """True when the user's last game still has an unfinished post-game presser, so
    the news/inbound modules should wait. Derived from the interview store (the
    single source of truth), not a separate flag, so it can never go stale."""
    try:
        from . import interview
        if dynasty is None:
            dynasty = load_dynasty(year)
        return interview.pending(year, dynasty) is not None
    except Exception:
        return False


def run_full(*, year: int | None = None, week: int | None = None, regenerate: bool = False,
             only: tuple[str, ...] | None = None, force_news: bool = False,
             regen_keys: tuple[str, ...] | None = None) -> dict[str, Any]:
    """Run every module for a week, with progress reporting for the UI.

    The presser gate lives here so EVERY path that regenerates (advance, the
    watcher, prewarm, an /api/generate call) respects it: while a presser is owed,
    the news/inbound modules are held back unless `force_news` is set or `only`
    names them explicitly (run_post_presser, after the presser completes).

    `regen_keys` force-regenerates just those modules while serving every other
    module from cache (and generating only what is missing). The post-presser pass
    uses it to rewrite the post-game coverage and, in the same pass, build any
    weekly module that was deferred until the coach finished speaking."""
    ptr = current_pointer()
    year = year if year is not None else ptr["year"]
    week = week if week is not None else ptr["week"]

    with _lock:
        _status.update({"running": True, "module": None, "progress": 0,
                        "total": len(REGISTRY), "week": week})
        results: dict[str, Any] = {}
        try:
            dynasty = load_dynasty(year, week)
            _seed_narrative(dynasty, year, week)
            held: set[str] = set()
            if only is None and not force_news and presser_owed(year, dynasty):
                held = set(HELD_FOR_PRESSER)
            regen = set(regen_keys or ())
            for i, (key, module) in enumerate(REGISTRY.items()):
                if only is not None and key not in only:
                    continue
                if key in held:
                    continue
                _status.update({"module": key, "progress": i})
                progress.set_sub_step(None)
                # Force a fresh generation for a globally-regenerate pass or for a
                # specifically targeted key; otherwise serve the cache and generate
                # only the misses.
                force = regenerate or key in regen
                if not force:
                    cached = cache.get_module(year, week, key)
                    if cached is not None:
                        results[key] = cached
                        continue
                content = module.generate(dynasty, year=year, week=week,
                                          use_llm=llm_settings.use_llm(), regenerate=force)
                cache.set_module(year, week, key, content)
                results[key] = content
            _status.update({"progress": len(REGISTRY)})
        finally:
            _status.update({"running": False, "module": None})
    return results


def run_post_presser(year: int, week: int) -> dict[str, Any]:
    """Generate everything owed once the post-game press conference is done.

    A single serialized pass that, now that the coach has spoken:
      * force-regenerates the post-game coverage (HELD_FOR_PRESSER) so it reflects
        the result AND his answers, replacing the week's pre-game articles, and
      * generates any other module not yet built for the week, serving the rest
        from cache.

    The second half is what makes the "Simulate & Advance" path smooth: when a
    game finishes, the whole week's generation is deferred until the presser is
    done (so the coach's answers feed all of it, not just the news), and this is
    what builds it. On a "Simulate Game" (same week), the weekly modules are
    already cached and pass through untouched; only the post-game coverage is
    rewritten. Called when a presser completes (or is skipped)."""
    return run_full(year=year, week=week, force_news=True, regen_keys=HELD_FOR_PRESSER)


def run_post_presser_async(year: int, week: int) -> None:
    """Run the post-presser generation in the background so the interview endpoint
    returns immediately. The frontend pulls the results in once the pass finishes
    (it polls /api/status) WITHOUT a blocking overlay, so the coach can look around
    while the week fills in. Serialized with other generation by _lock."""
    threading.Thread(target=run_post_presser, args=(year, week), daemon=True).start()


def is_week_cached(year: int, week: int) -> bool:
    """True when every registered module already has cached content for a week."""
    cached = cache.get_week(year, week)
    return all(key in cached for key in REGISTRY)


def prewarm_async() -> None:
    """Generate any missing modules for the current week in the background, so the
    full slate is ready when the user opens the app instead of each tab generating
    on first visit. A no-op once the week is fully cached, so repeat launches are
    free. Already-running generation (a lock contention) is simply skipped."""
    ptr = current_pointer()
    if is_week_cached(ptr["year"], ptr["week"]) or _status.get("running"):
        return
    # Hold off entirely while a presser is owed: run_full would generate the
    # non-news modules and (correctly) skip the held ones, but the next prewarm
    # would just no-op, so there is nothing to gain by racing the coach's answers.
    if presser_owed(ptr["year"]):
        return
    threading.Thread(
        target=run_full, kwargs={"year": ptr["year"], "week": ptr["week"]}, daemon=True
    ).start()


def advance_to(year: int, week: int, *, regenerate: bool = False) -> dict[str, Any]:
    """Move the current pointer and run the full pipeline for the new week.

    If the user's last game still owes a post-game presser (the common case: a
    week was advanced right after a game), DEFER the week's generation entirely.
    The press conference runs first and run_post_presser builds the week once the
    coach has spoken, so his answers feed all of it (not just the news) and nobody
    waits on a loading screen before the interview."""
    set_pointer(year, week)
    dynasty = load_dynasty(year, week)
    new_coach = detect_coaching_change(dynasty)
    results = {} if presser_owed(year, dynasty) else run_full(year=year, week=week, regenerate=regenerate)
    if new_coach:
        from .modules import hot_seat
        results["coaching_search"] = hot_seat.coaching_search(
            dynasty["team"]["name"], dynasty, use_llm=llm_settings.use_llm())
    return results


# --- reacting to the save -------------------------------------------------
def save_hash() -> str | None:
    """The content hash of the current save, surfaced to the UI so it can refresh
    on a same-week edit (a hash change without a pointer advance)."""
    save = _read_save()
    return save["meta"].get("hash") if save else None


def sync_from_save() -> dict[str, Any] | None:
    """Reconcile the companion to the live save. Returns a small outcome dict when
    something changed, else None. Drives the watcher and runs once on boot.

    Dispatch:
      * different dynasty (meta.dynasty_id changed) -> switch to it (which re-scopes
        every per-dynasty store to its own isolated directory) and generate; nothing
        to wipe, a new dynasty starts with empty stores
      * forward advance        -> advance_to (full regen + coaching-change search,
        UNLESS a presser is owed, in which case generation is deferred to it)
      * same week, game played  -> a post-game presser is owed: leave the week's
        content (recruiting, portal, awards... + the pre-game articles) in place
        and let the post-game news wait for the presser (run_post_presser)
      * same week, other edit   -> a Simulator-side edit (roster / NIL): clear that
        week + regen
    """
    from . import dynasties
    save = _read_save()
    if save is None:
        return None
    s_year = int(save["season"]["year"])
    s_week = int(save["season"]["week"])
    s_hash = save["meta"].get("hash")
    s_id = (save.get("meta") or {}).get("dynasty_id")

    # A different dynasty than the one we are pointed at: switch to it (this
    # re-scopes every per-dynasty store) and generate against its own isolated
    # data. No wiping needed: a new dynasty has its own empty directory.
    if s_id and s_id != dynasties.current_id():
        dynasties.upsert_from_save(save)  # registers + makes it current
        _archive(save, s_year, s_week)
        set_pointer(s_year, s_week)
        run_full(year=s_year, week=s_week)
        state = _load_app_state()
        state["last_seen_hash"] = s_hash
        _save_app_state(state)
        return {"outcome": "new_dynasty", "year": s_year, "week": s_week}

    _archive(save, s_year, s_week)

    state = _load_app_state()
    ptr = (state["year"], state["week"])
    if (s_year, s_week) == ptr and s_hash == state.get("last_seen_hash"):
        return None  # nothing meaningful changed

    if (s_year, s_week) > ptr:
        advance_to(s_year, s_week)
        outcome = "advance"
    elif presser_owed(s_year, save):
        # A game just completed in the current week. The weekly content was
        # generated going into the week and stands; only the post-game news
        # regenerates, and that waits for the presser. Leave the week untouched so
        # the pre-game articles stay up until then.
        set_pointer(s_year, s_week)
        outcome = "post_game"
    else:
        set_pointer(s_year, s_week)
        cache.clear_week(s_year, s_week)
        run_full(year=s_year, week=s_week)
        outcome = "refresh"

    state = _load_app_state()
    state["last_seen_hash"] = s_hash
    _save_app_state(state)
    return {"outcome": outcome, "year": s_year, "week": s_week}
