"""Campus locations for every FBS program, keyed by espn_id.

Used for playoff game sites: a first-round game at the higher seed's stadium is
labeled with the school's home city/state, like the broadcast bracket graphics
("AUSTIN, TX", "COLUMBUS, OH"). The city is where the team actually plays its
home games (Miami -> Miami Gardens, UCLA -> Pasadena, Penn State -> State
College). Neither the league seed nor the save carries this, so it is static
reference data; the save's stadium table (~25MB region) can replace it once
that region is decoded and mapped.
"""
from __future__ import annotations

CAMPUS_SITES: dict[int, str] = {
    # ACC
    228: "Clemson, SC",
    52: "Tallahassee, FL",
    2390: "Miami Gardens, FL",
    97: "Louisville, KY",
    2567: "Dallas, TX",
    59: "Atlanta, GA",
    152: "Raleigh, NC",
    221: "Pittsburgh, PA",
    153: "Chapel Hill, NC",
    259: "Blacksburg, VA",
    25: "Berkeley, CA",
    150: "Durham, NC",
    24: "Stanford, CA",
    258: "Charlottesville, VA",
    103: "Chestnut Hill, MA",
    183: "Syracuse, NY",
    154: "Winston-Salem, NC",
    # American
    2655: "New Orleans, LA",
    349: "West Point, NY",
    235: "Memphis, TN",
    2426: "Annapolis, MD",
    2429: "Charlotte, NC",
    242: "Houston, TX",
    2636: "San Antonio, TX",
    151: "Greenville, NC",
    249: "Denton, TX",
    5: "Birmingham, AL",
    58: "Tampa, FL",
    202: "Tulsa, OK",
    2226: "Boca Raton, FL",
    218: "Philadelphia, PA",
    # Big 12
    254: "Salt Lake City, UT",
    2306: "Manhattan, KS",
    9: "Tempe, AZ",
    252: "Provo, UT",
    66: "Ames, IA",
    2641: "Lubbock, TX",
    2628: "Fort Worth, TX",
    38: "Boulder, CO",
    2305: "Lawrence, KS",
    239: "Waco, TX",
    197: "Stillwater, OK",
    2132: "Cincinnati, OH",
    277: "Morgantown, WV",
    248: "Houston, TX",
    12: "Tucson, AZ",
    2116: "Orlando, FL",
    # Big Ten
    194: "Columbus, OH",
    2483: "Eugene, OR",
    130: "Ann Arbor, MI",
    213: "State College, PA",
    30: "Los Angeles, CA",
    264: "Seattle, WA",
    2294: "Iowa City, IA",
    84: "Bloomington, IN",
    275: "Madison, WI",
    158: "Lincoln, NE",
    127: "East Lansing, MI",
    2509: "West Lafayette, IN",
    356: "Champaign, IL",
    135: "Minneapolis, MN",
    77: "Evanston, IL",
    26: "Pasadena, CA",
    120: "College Park, MD",
    164: "Piscataway, NJ",
    # Conference USA
    2335: "Lynchburg, VA",
    2348: "Ruston, LA",
    2393: "Murfreesboro, TN",
    98: "Bowling Green, KY",
    2229: "Miami, FL",
    338: "Kennesaw, GA",
    2534: "Huntsville, TX",
    2623: "Springfield, MO",
    166: "Las Cruces, NM",
    48: "Newark, DE",
    55: "Jacksonville, AL",
    2638: "El Paso, TX",
    # Independents
    87: "South Bend, IN",
    41: "East Hartford, CT",
    # MAC
    2006: "Akron, OH",
    2050: "Muncie, IN",
    195: "Athens, OH",
    2084: "Buffalo, NY",
    2309: "Kent, OH",
    113: "Amherst, MA",
    193: "Oxford, OH",
    2199: "Ypsilanti, MI",
    2649: "Toledo, OH",
    2117: "Mount Pleasant, MI",
    2459: "DeKalb, IL",
    2711: "Kalamazoo, MI",
    189: "Bowling Green, OH",
    # Mountain West
    68: "Boise, ID",
    2439: "Las Vegas, NV",
    278: "Fresno, CA",
    62: "Honolulu, HI",
    2005: "Colorado Springs, CO",
    2751: "Laramie, WY",
    167: "Albuquerque, NM",
    23: "San Jose, CA",
    328: "Logan, UT",
    21: "San Diego, CA",
    2440: "Reno, NV",
    36: "Fort Collins, CO",
    265: "Pullman, WA",
    204: "Corvallis, OR",
    # SEC
    61: "Athens, GA",
    251: "Austin, TX",
    333: "Tuscaloosa, AL",
    99: "Baton Rouge, LA",
    2633: "Knoxville, TN",
    145: "Oxford, MS",
    201: "Norman, OK",
    245: "College Station, TX",
    142: "Columbia, MO",
    57: "Gainesville, FL",
    2579: "Columbia, SC",
    2: "Auburn, AL",
    8: "Fayetteville, AR",
    96: "Lexington, KY",
    238: "Nashville, TN",
    344: "Starkville, MS",
    # Sun Belt
    256: "Harrisonburg, VA",
    2032: "Jonesboro, AR",
    295: "Norfolk, VA",
    2572: "Hattiesburg, MS",
    2653: "Troy, AL",
    2247: "Atlanta, GA",
    276: "Huntington, WV",
    6: "Mobile, AL",
    309: "Lafayette, LA",
    2433: "Monroe, LA",
    290: "Statesboro, GA",
    326: "San Marcos, TX",
    2026: "Boone, NC",
    324: "Conway, SC",
}


def campus_city(espn_id: object) -> str | None:
    try:
        return CAMPUS_SITES.get(int(espn_id))  # type: ignore[arg-type]
    except (TypeError, ValueError):
        return None


# Home stadium display names, keyed by the school name exactly as the save's
# team table spells it (teams.parse_teams). The save stores stadiums as opaque
# uid handles with no name data, so the neutral-site picker joins the save's
# team -> stadium link with this table for labels. Schools missing here fall
# back to "<School> home stadium".
STADIUM_NAMES: dict[str, str] = {
    "Air Force": "Falcon Stadium",
    "Akron": "InfoCision Stadium",
    "Alabama": "Bryant-Denny Stadium",
    "Appalachian State": "Kidd Brewer Stadium",
    "Arizona": "Arizona Stadium",
    "Arizona State": "Mountain America Stadium",
    "Arkansas": "Razorback Stadium",
    "Arkansas State": "Centennial Bank Stadium",
    "Army": "Michie Stadium",
    "Auburn": "Jordan-Hare Stadium",
    "Ball State": "Scheumann Stadium",
    "Baylor": "McLane Stadium",
    "Boise State": "Albertsons Stadium",
    "Boston College": "Alumni Stadium",
    "Bowling Green": "Doyt Perry Stadium",
    "Buffalo": "UB Stadium",
    "BYU": "LaVell Edwards Stadium",
    "California": "California Memorial Stadium",
    "Central Michigan": "Kelly/Shorts Stadium",
    "Charlotte": "Jerry Richardson Stadium",
    "Cincinnati": "Nippert Stadium",
    "Clemson": "Memorial Stadium (Clemson)",
    "Coastal Carolina": "Brooks Stadium",
    "Colorado": "Folsom Field",
    "Colorado State": "Canvas Stadium",
    "UConn": "Rentschler Field",
    "Delaware": "Delaware Stadium",
    "Duke": "Wallace Wade Stadium",
    "Eastern Michigan": "Rynearson Stadium",
    "East Carolina": "Dowdy-Ficklen Stadium",
    "Florida International": "Riccardo Silva Stadium",
    "Florida": "Ben Hill Griffin Stadium",
    "Florida Atlantic": "FAU Stadium",
    "Florida State": "Doak Campbell Stadium",
    "Fresno State": "Valley Children's Stadium",
    "Georgia": "Sanford Stadium",
    "Georgia Southern": "Paulson Stadium",
    "Georgia State": "Center Parc Stadium",
    "Georgia Tech": "Bobby Dodd Stadium",
    "Hawai'i": "Clarence T.C. Ching Complex",
    "Houston": "TDECU Stadium",
    "Illinois": "Memorial Stadium (Champaign)",
    "Indiana": "Memorial Stadium (Bloomington)",
    "Iowa": "Kinnick Stadium",
    "Iowa State": "Jack Trice Stadium",
    "Jacksonville State": "Burgess-Snow Field",
    "James Madison": "Bridgeforth Stadium",
    "Kansas": "David Booth Kansas Memorial Stadium",
    "Kansas State": "Bill Snyder Family Stadium",
    "Kennesaw State": "Fifth Third Stadium",
    "Kent State": "Dix Stadium",
    "Kentucky": "Kroger Field",
    "Liberty": "Williams Stadium",
    "Louisiana": "Cajun Field",
    "Louisiana Tech": "Joe Aillet Stadium",
    "Louisville": "L&N Federal Credit Union Stadium",
    "LSU": "Tiger Stadium",
    "Marshall": "Joan C. Edwards Stadium",
    "Maryland": "SECU Stadium",
    "Memphis": "Simmons Bank Liberty Stadium",
    "Miami": "Hard Rock Stadium",
    "Miami University": "Yager Stadium",
    "Michigan": "Michigan Stadium",
    "Michigan State": "Spartan Stadium",
    "Middle Tennessee": "Floyd Stadium",
    "Minnesota": "Huntington Bank Stadium",
    "Mississippi State": "Davis Wade Stadium",
    "Missouri": "Faurot Field",
    "Missouri State": "Plaster Stadium",
    "Navy": "Navy-Marine Corps Memorial Stadium",
    "NC State": "Carter-Finley Stadium",
    "Nebraska": "Memorial Stadium (Lincoln)",
    "Nevada": "Mackay Stadium",
    "New Mexico": "University Stadium",
    "New Mexico State": "Aggie Memorial Stadium",
    "North Carolina": "Kenan Stadium",
    "North Dakota State": "Fargodome",
    "North Texas": "DATCU Stadium",
    "Northern Illinois": "Huskie Stadium",
    "Northwestern": "Ryan Field",
    "Notre Dame": "Notre Dame Stadium",
    "Ohio": "Peden Stadium",
    "Ohio State": "Ohio Stadium",
    "Oklahoma": "Gaylord Family Oklahoma Memorial Stadium",
    "Oklahoma State": "Boone Pickens Stadium",
    "Old Dominion": "S.B. Ballard Stadium",
    "Ole Miss": "Vaught-Hemingway Stadium",
    "Oregon": "Autzen Stadium",
    "Oregon State": "Reser Stadium",
    "Penn State": "Beaver Stadium",
    "Pittsburgh": "Acrisure Stadium",
    "Purdue": "Ross-Ade Stadium",
    "Rice": "Rice Stadium",
    "Rutgers": "SHI Stadium",
    "Sacramento State": "Hornet Stadium",
    "Sam Houston": "Bowers Stadium",
    "San Diego State": "Snapdragon Stadium",
    "San Jose State": "CEFCU Stadium",
    "SMU": "Gerald J. Ford Stadium",
    "South Alabama": "Hancock Whitney Stadium",
    "South Carolina": "Williams-Brice Stadium",
    "Southern Mississippi": "M.M. Roberts Stadium",
    "Stanford": "Stanford Stadium",
    "Syracuse": "JMA Wireless Dome",
    "TCU": "Amon G. Carter Stadium",
    "Temple": "Lincoln Financial Field",
    "Tennessee": "Neyland Stadium",
    "Texas": "Darrell K Royal-Texas Memorial Stadium",
    "Texas A&M": "Kyle Field",
    "Texas State": "UFCU Stadium",
    "Texas Tech": "Jones AT&T Stadium",
    "Toledo": "Glass Bowl",
    "Troy": "Veterans Memorial Stadium",
    "Tulane": "Yulman Stadium",
    "Tulsa": "H.A. Chapman Stadium",
    "UAB": "Protective Stadium",
    "UCF": "FBC Mortgage Stadium",
    "UCLA": "Rose Bowl",
    "UL Monroe": "Malone Stadium",
    "UMass": "McGuirk Alumni Stadium",
    "UNLV": "Allegiant Stadium",
    "USC": "Los Angeles Memorial Coliseum",
    "USF": "Raymond James Stadium",
    "Utah": "Rice-Eccles Stadium",
    "Utah State": "Maverik Stadium",
    "UTEP": "Sun Bowl",
    "UTSA": "Alamodome",
    "Vanderbilt": "FirstBank Stadium",
    "Virginia": "Scott Stadium",
    "Virginia Tech": "Lane Stadium",
    "Wake Forest": "Allegacy Stadium",
    "Washington": "Husky Stadium",
    "Washington State": "Gesa Field",
    "West Virginia": "Milan Puskar Stadium",
    "Western Kentucky": "Houchens-Smith Stadium",
    "Western Michigan": "Waldo Stadium",
    "Wisconsin": "Camp Randall Stadium",
    "Wyoming": "War Memorial Stadium",
}


def stadium_name(school: str) -> str | None:
    return STADIUM_NAMES.get(school)
